### ISSUE TITLE
Indicator ordering - high priority

### ISSUE THREAD

**Issue by japartridge** [MAPC/regionalindicators#21]
As a site admin, I would like to be able to add a new indicator or indicator group and be able to place it in any order. So that, for example, if we develop a new indicator and want to insert it into the middle of a section of the report that is already published, we can do so. Currently, it seems new indicators show up at the bottom of their Subject section, no matter how I try to order them.

**Comment by allthesignals** [comment]
Recent commit accomplishes this.
