### ISSUE TITLE
Cannot remove an indicator from an indicator group

### ISSUE THREAD

**Issue by japartridge** [MAPC/regionalindicators#22]
I would like to be able to remove an indicator from a group, but currently I get an error message when I save after trying to do so.

**Comment by allthesignals** [comment]
Having trouble reproducing this issue. Could we get the error message when you see it again @japartridge

**Comment by allthesignals** [comment]
NoMethodError in RailsAdmin::MainController#edit

undefined method `name' for nil:NilClass

Params:
{"utf8"=>"✓",
"_method"=>"put",
"authenticity_token"=>"eh3a2NrqIp72saAEj1OOwpzt7Hwo2Vn/MWs2RsKcvJM=",
"indicator_group"=>{"title"=>"Segregation Across Life Stages",
"position"=>"0",
"indicator_ids"=>["",
"",
"469",
"470",
"496"],
"explanation_attributes"=>{"narrative"=>"",
"explainable_id"=>"62",
"explainable_type"=>"IndicatorGroup",
"source_ids"=>["",
""],
"id"=>"238"}},
"return_to"=>"http://localhost:3000/admin/indicator_group",
"_add_edit"=>"",
"model_name"=>"indicator_group",
"id"=>"62"}

PUT on indicator_group/62/edit.
