### ISSUE TITLE
Edits to the Title field of a Topic Area affect the home page layout

### ISSUE THREAD

**Issue by TimReardon** [MAPC/regionalindicators#24]
I notice the Transportation Indicators are called "Transportation Choices" on the home page, when it should be Sustainable Transportation.  I tried changing it through the admin console, but any text other than the original caused the text to move up the page and changed the color of the circle, or eliminated it entirely.  A random train shows up with one combination.  Totally bizarre.  You can see the layout that results from various combinations of text in the attached images.  Can we resolve this enough to have the correct title for Transportation?  As soon as possible would be nice, but hard deadline is Feb 28 for SOE release.  

![screen shot 2017-02-14 at 11 29 42 pm](https://cloud.githubusercontent.com/assets/2146679/22960718/14e74a7a-f30e-11e6-81bd-7dbd2e70dbb7.png)
![screen shot 2017-02-14 at 11 29 12 pm](https://cloud.githubusercontent.com/assets/2146679/22960720/14f06d1c-f30e-11e6-9c84-3c684ece74e1.png)
![screen shot 2017-02-14 at 11 28 40 pm](https://cloud.githubusercontent.com/assets/2146679/22960719/14efc934-f30e-11e6-83f9-889ed5690df0.png)

**Comment by allthesignals** [comment]
the reason the site broke when changing the transportation title is that the styling class name is hard-coded to point to transportation-choices, so when the title changed it lost all the styling. this should be fixed. if we need to change topic area titles, someone has to go in and change the CSS as well (poor design decision!).
